/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_capston_MainActivity */

#ifndef _Included_com_example_capston_MainActivity
#define _Included_com_example_capston_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_capston_MainActivity_ACTION_MANAGE_OVERLAY_PERMISSION_REQUEST_CODE
#define com_example_capston_MainActivity_ACTION_MANAGE_OVERLAY_PERMISSION_REQUEST_CODE 1L
#undef com_example_capston_MainActivity_REQUEST_ENABLE_BT
#define com_example_capston_MainActivity_REQUEST_ENABLE_BT 10L
/*
 * Class:     com_example_capston_MainActivity
 * Method:    loadCascade
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_example_capston_MainActivity_loadCascade
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
