/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_capston_CamService */

#ifndef _Included_com_example_capston_CamService
#define _Included_com_example_capston_CamService
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_capston_CamService_ONGOING_NOTIFICATION_ID
#define com_example_capston_CamService_ONGOING_NOTIFICATION_ID 6660L
/*
 * Class:     com_example_capston_CamService
 * Method:    detect
 * Signature: (JJJJJ)I
 */
JNIEXPORT jint JNICALL Java_com_example_capston_CamService_detect
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
