/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_capston_settings */

#ifndef _Included_com_example_capston_settings
#define _Included_com_example_capston_settings
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_capston_settings_CAMERA_PERMISSION_REQUEST_CODE
#define com_example_capston_settings_CAMERA_PERMISSION_REQUEST_CODE 200L
/*
 * Class:     com_example_capston_settings
 * Method:    detect
 * Signature: (JJJJJ)I
 */
JNIEXPORT jint JNICALL Java_com_example_capston_Settings_detect
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
